'use strict';

/*
    Простой скрипт для генерации из svg файлов React-компонентов
*/

const fs = require('fs-extra');
let list = fs.readdirSync('./country-list-master/data/');
let iconsExport = '';
let iconsImport = '';
let res = '';

list.forEach((fName, index, arr) => {
    let contries = fs.readFileSync('./country-list-master/data/' + fName + '/country.json', 'utf8');
    contries = JSON.parse(contries);
    let countriesList = [];

    for(let k in contries){
        countriesList.push({value: k, name: contries[k]});
    }

    //countriesList = countriesList.sort((a, b) => a.name > b.name ? 1 : a.name < b.name ? -1 : 0);

    res = `/**
 * !!!!!!!!!!!!!!!!!!!!!!!!!!
 * NOTE: This file is auto generated. Do not edit this file manually.
 */

export const countries_${fName}:{value:string, name:string}[] = ${JSON.stringify(countriesList, undefined, '    ')};
`;
    fs.writeFileSync(`./src/localization/countries/${fName}.ts`, res);
});
