'use strict';

/*
    Простой скрипт для генерации из svg файлов React-компонентов
*/

const fs = require('fs-extra');
let list = fs.readdirSync('./icons');
let iconsExport = '';
let iconsImport = '';
let res = '';

list.forEach((fName, index, arr)=>{
    if(fName[0] !== '.'){
        var compName = fName.replace(/(fa)?(.*)\.svg/, function(str, a, f){
            f = f[0].toUpperCase() + f.substring(1);
            return 'Icon' + f.replace(/-(\w)/g, function(str, f){
                return f.toUpperCase();
            });
        });
        var contents = fs.readFileSync('./icons/' + fName, 'utf8');
        fs.writeFileSync("./src/components/icons/"+compName+'.tsx', generateComponent(contents, compName));

        iconsExport += `import { ${compName} } from './${compName}';` + '\n';
        iconsImport += `    ${compName}` + (index < arr.length - 1 ? ',\n' : '');
    }
});

res = `/**
 * !!!!!!!!!!!!!!!!!!!!!!!!!!
 * NOTE: This file is auto generated. Do not edit this file manually.
 */

${iconsExport}
export {
${iconsImport}
};
`;

fs.writeFileSync("./src/components/icons/index.ts", res);

function generateComponent(svgContent, componentName){

    svgContent = svgContent.replace('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">', '<svg viewBox="0 0 32 32" width="1em" height="1em" fill="currentColor">');

    let compTemplate = `import React from 'react';

export const ${componentName} = () => (
    ${svgContent}
);
`;

    return compTemplate;
}